import Foundation

public enum SQLKeywords {
    public static let list: [String] = """
    ABORT ADD ALL ALTER ALWAYS ANALYZE AND ANY ARRAY AS ASC ASYMMETRIC ATOMIC AUTHORIZATION BEGIN BETWEEN \
    BIGINT BOTH BY CACHE CALL CASCADE CASE CAST CHECK CHECKPOINT CLUSTER COLLATE COLUMN COMMENT COMMIT \
    CONCURRENTLY CONFLICT CONSTRAINT CONSTRAINTS COPY CREATE CROSS CUBE CURRENT CURRENT_DATE CURRENT_ROLE \
    CURRENT_TIME CURRENT_TIMESTAMP CURRENT_USER CURSOR CYCLE DATABASE DEALLOCATE DECLARE DEFAULT DEFERRABLE \
    DEFERRED DELETE DESC DISCARD DISTINCT DO DOMAIN DROP EACH ELSE END ESCAPE EXCEPT EXCLUDE EXECUTE EXISTS \
    EXPLAIN EXTENSION FALSE FETCH FILTER FIRST FOLLOWING FOR FOREIGN FROM FULL FUNCTION GENERATED GRANT GROUP \
    GROUPING HAVING IF ILIKE IMMUTABLE IN INDEX INHERITS INITIALLY INNER INSERT INSTEAD INTERSECT INTO IS \
    ISNULL JOIN KEY LANGUAGE LAST LATERAL LEADING LEFT LIKE LIMIT LISTEN LOCAL LOCK MATCHED MATERIALIZED \
    MERGE NATURAL NO NOT NOTHING NOTIFY NOTNULL NOWAIT NULL NULLS OF OFF OFFSET ON ONLY OR ORDER OUTER OVER \
    OVERLAPS OWNER PARTITION PLACING POLICY PRECEDING PREPARE PRIMARY PROCEDURE PUBLICATION RANGE RECURSIVE \
    REFERENCES REFRESH REINDEX RELEASE RENAME REPLACE RESET RESTART RESTRICT RETURNING RETURNS REVOKE RIGHT \
    ROLE ROLLBACK ROLLUP ROW ROWS RULE SAVEPOINT SCHEMA SECURITY SELECT SEQUENCE SESSION_USER SET SETOF SHOW \
    SIMILAR SOME STABLE START STRICT SYMMETRIC TABLE TABLESAMPLE TABLESPACE TEMP TEMPORARY THEN TIES TO \
    TRAILING TRANSACTION TRIGGER TRUE TRUNCATE TYPE UNBOUNDED UNION UNIQUE UNLISTEN UNLOGGED UPDATE USING \
    USER VACUUM VALUES VARIADIC VERBOSE VIEW VOLATILE WHEN WHERE WINDOW WITH WITHIN WITHOUT ZONE
    """.split(separator: " ").map(String.init)

    public static let all: Set<String> = Set(list)
}
